### PR TITLE
Handle HTTP 304s when setting span status

### PR DESCRIPTION
**Pull request by akshayjshah**
If the RPC is using the Connect protocol and returns a not modified
error, we shouldn't set the span status to error. Follow-up to #120.

### CODE REVIEW

**Comment by joshcarp** [comment]
This also brings up the problem that ~3 months ago there was a breaking change to how grpc span statuses are set in the opentelemetry specification: https://github.com/open-telemetry/opentelemetry-specification/pull/3333 

Table as follows:



gRPC Status Code | SpanKind.SERVER Span Status | SpanKind.CLIENT Span Status
-- | -- | --
OK | unset | unset
CANCELLED | unset | Error
UNKNOWN | Error | Error
INVALID_ARGUMENT | unset | Error
DEADLINE_EXCEEDED | Error | Error
NOT_FOUND | unset | Error
ALREADY_EXISTS | unset | Error
PERMISSION_DENIED | unset | Error
RESOURCE_EXHAUSTED | unset | Error
FAILED_PRECONDITION | unset | Error
ABORTED | unset | Error
OUT_OF_RANGE | unset | Error
UNIMPLEMENTED | Error | Error
INTERNAL | Error | Error
UNAVAILABLE | Error | Error
DATA_LOSS | Error | Error
UNAUTHENTICATED | unset | Error

**Comment by jhump** [comment]
@akshayjshah, I pushed a commit with a test.

@joshcarp, maybe file that as a separate issue? Maybe we can address that in subsequent PR -- and maybe even subsequent release? Ideally, we'd get this fix out soon since the current release is causing unnecessary alerts in the BSR.

**Review by jhump — APPROVED** [review]
LGTM. You may want to take a look at my test and revise if you see a better way to do this (or are unhappy with the buf lint exclusions I added).

**Comment by akshayjshah** [comment]
Thanks for the test case, @jhump! I pushed a small change to make the `Ping` method idempotent rather than introducing a new one, but the test logic itself looks great.

**Pull request merged**
