### PR TITLE
Upgrade the otel  from 1.15.1/v0.38.1 to version 1.16.0/0.39.0

### PR DESCRIPTION
**Pull request by Tochemey**

### CODE REVIEW

**Comment by Tochemey** [comment]
@joshcarp can you take a look at this?

**Comment by Tochemey** [comment]
@akshayjshah and @joshcarp the PR Approval Bypass Notifier step seems broken.😉

**Review by joshcarp — APPROVED** [review]
LGTM, thanks @Tochemey

**Comment by joshcarp** [comment]
https://github.com/bufbuild/connect-opentelemetry-go/releases/tag/v0.3.0 has been released

**Pull request merged**
